# SPDX-License-Identifier: Apache-2.0

[package]
name = "xlsynth-symex"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Symbolic evaluation of pure XLS functions"
repository = "https://github.com/qobilidop/xlsynth-symex"

[dependencies]
xlsynth = { git = "https://github.com/xlsynth/xlsynth-crate", rev = "92bc9b932981c776bb4bb197cd6b6726f17ec090" }

[lints.rust]
missing_docs = "warn"

[lints.clippy]
all = "warn"
